// Generated by gencpp from file service/person.msg
// DO NOT EDIT!


#ifndef SERVICE_MESSAGE_PERSON_H
#define SERVICE_MESSAGE_PERSON_H

#include <ros/service_traits.h>


#include <service/personRequest.h>
#include <service/personResponse.h>


namespace service
{

struct person
{

typedef personRequest Request;
typedef personResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct person
} // namespace service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service::person > {
  static const char* value()
  {
    return "c198113e7dd9cc5c9fd5f271c8479b39";
  }

  static const char* value(const ::service::person&) { return value(); }
};

template<>
struct DataType< ::service::person > {
  static const char* value()
  {
    return "service/person";
  }

  static const char* value(const ::service::person&) { return value(); }
};


// service_traits::MD5Sum< ::service::personRequest> should match 
// service_traits::MD5Sum< ::service::person > 
template<>
struct MD5Sum< ::service::personRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service::person >::value();
  }
  static const char* value(const ::service::personRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service::personRequest> should match 
// service_traits::DataType< ::service::person > 
template<>
struct DataType< ::service::personRequest>
{
  static const char* value()
  {
    return DataType< ::service::person >::value();
  }
  static const char* value(const ::service::personRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service::personResponse> should match 
// service_traits::MD5Sum< ::service::person > 
template<>
struct MD5Sum< ::service::personResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service::person >::value();
  }
  static const char* value(const ::service::personResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service::personResponse> should match 
// service_traits::DataType< ::service::person > 
template<>
struct DataType< ::service::personResponse>
{
  static const char* value()
  {
    return DataType< ::service::person >::value();
  }
  static const char* value(const ::service::personResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_MESSAGE_PERSON_H
